export enum USER_PRESENT_DATA {
  USER_PRESENT_DATA_REQUEST = 'USER_PRESENT_DATA_REQUEST',
  USER_PRESENT_DATA_SUCCESS = 'USER_PRESENT_DATA_SUCCESS',
  USER_PRESENT_DATA_FAILURE = 'USER_PRESENT_DATA_FAILURE'
}

export const USER_PRESENT_DATA_ACTION = params => ({
  type: USER_PRESENT_DATA.USER_PRESENT_DATA_REQUEST,
  params
})
