export enum REQUEST_USER_PRESENT_DATA {
  MAKE_USER_PRESENT_REQUEST = 'MAKE_USER_PRESENT_REQUEST',
  REQUEST_USER_DATA_PRESENT_SUCCESS = 'REQUEST_USER_DATA_PRESENT_SUCCESS',
  REQUEST_USER_DATA_PRESENT_FAILURE = 'REQUEST_USER_DATA_PRESENT_FAILURE'
}

export const UserPresentRequest = params => ({
  type: REQUEST_USER_PRESENT_DATA.MAKE_USER_PRESENT_REQUEST,
  params
})
