export enum USER_DATA {
  USER_DATA_REQUEST = 'USER_DATA_REQUEST',
  USER_DATA_SUCCESS = 'USER_DATA_SUCCESS',
  USER_DATA_FAILURE = 'USER_DATA_FAILURE'
}

export const USER_DATA_ACTION = params => ({
  type: USER_DATA.USER_DATA_REQUEST,
  params
})
