export enum LOGIN_USER {
  LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
}

export const LOGIN_USER_ACTION = params => ({
  type: LOGIN_USER.LOGIN_USER_REQUEST,
  params
})
